version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.simple
    ports:
      - "3000:3000"
    environment:
      # Pass environment variables at runtime (SECURE)
      - NODE_ENV=${NODE_ENV:-development}
      - POSTGRES_URL=${POSTGRES_URL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - API_KEY=${API_KEY}
      - SHEET_ID=${SHEET_ID}
      - DATABASE_URL=${DATABASE_URL}
      - NEXT_PUBLIC_STACK_PROJECT_ID=${NEXT_PUBLIC_STACK_PROJECT_ID}
      - NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY=${NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY}
      - STACK_SECRET_SERVER_KEY=${STACK_SECRET_SERVER_KEY}
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    volumes:
      # Mount source code for development
      - .:/app
      - /app/node_modules
      - /app/.next